name = "bazi-fortune-api"
main = "src/index.ts"
compatibility_date = "2023-06-20"

# 环境变量配置
[vars]
JWT_SECRET = "your-jwt-secret-key-change-in-production"

# 生产环境配置
[env.production]
name = "bazi-fortune-api-prod"

[env.production.vars]
DATABASE_URL = "postgresql://postgres:[YOUR-PASSWORD]@db.[YOUR-PROJECT-REF].supabase.co:5432/postgres"
JWT_SECRET = "[YOUR-JWT-SECRET]"
DEEPSEEK_API_KEY = "[YOUR-DEEPSEEK-API-KEY]"
OPENAI_API_KEY = "[YOUR-OPENAI-API-KEY]"

# KV存储（用于缓存）
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "[YOUR-KV-NAMESPACE-ID]"
preview_id = "[YOUR-KV-PREVIEW-ID]"

# D1数据库（可选，用于本地开发）
[[d1_databases]]
binding = "DB"
database_name = "bazi-fortune-db"
database_id = "local-database-id"

# 开发环境配置
[env.development]
name = "bazi-fortune-api-dev"

[env.development.vars]
DATABASE_URL = "postgresql://postgres:[YOUR-PASSWORD]@db.[YOUR-PROJECT-REF].supabase.co:5432/postgres"
JWT_SECRET = "dev-jwt-secret"
DEEPSEEK_API_KEY = "[YOUR-DEEPSEEK-API-KEY]"
OPENAI_API_KEY = "[YOUR-OPENAI-API-KEY]"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "[YOUR-KV-NAMESPACE-ID]"
preview_id = "[YOUR-KV-PREVIEW-ID]"