# 服务器配置
server:
  port: "8081"

# 数据库配置
# 支持 mysql / sqlite（开发用）
database:
  type: "sqlite"  # 可改为 "sqlite" 用于本地开发
  mysql:
    # 推荐使用环境变量注入，示例：MYSQL_DSN="user:pass@tcp(127.0.0.1:3306)/bazi_app?charset=utf8mb4&parseTime=True&loc=Local"
    dsn: "root:gemini4094@tcp(127.0.0.1:3306)/bazi_app?charset=utf8mb4&parseTime=True&loc=Local"
    max_open_conns: 100
    max_idle_conns: 10
    conn_max_life_seconds: 3600
  sqlite:
    path: "./bazi_app.db"

# 认证配置
auth:
  jwt_secret: "dev-secret-change-me"

# DeepSeek AI 配置（使用环境变量注入）
deepseek:
  api_key: ""
  api_base_url: "https://api.deepseek.com"

# OpenAI 配置（使用环境变量注入）
openai:
  api_key: ""
  api_base_url: "https://api.openai.com/v1"