name: bazi_fortune_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  get: ^4.7.2
  get_storage: ^2.1.1
  intl: ^0.20.2
  lunar: ^1.0.0
  http: ^1.2.2
  webview_flutter: ^4.7.0
  url_launcher: ^6.3.0
  flutter_inappwebview: ^6.0.0
  city_pickers: ^1.2.3
  wasm: ^0.1.0+1
  # 新增依赖
  flutter_screenutil: ^5.9.0
  flutter_otp_text_field: ^1.1.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/web/almanac_detail.html